Adding Arabic language
pdfme/pdfme pull request #100
Opened 2022-10-22 20:09 UTC by mhmdAljefri

2022-12-13 11:07 UTC, mhmdAljefri commented
hey @mohammed-bahumaish can you check this PR :pray:

2023-01-30 15:12 UTC, aalnussairi requested changes
minor changes requested, اختر is incorrect. It should be اختار. Otherwise, it's all good.

2023-01-30 15:12 UTC, aalnussairi commented on packages/ui/src/i18n.ts
> +  plsSelect: 'اختر',
يرجى الاختيار

2023-01-30 15:12 UTC, aalnussairi commented on packages/ui/src/i18n.ts
> +  select: 'اختر',
اختار

2023-01-30 15:12 UTC, aalnussairi commented on packages/ui/src/i18n.ts
> +  plsSelect: 'اختر',
Or 

الرجاء أختار

But the previous comment is more correct

2023-03-19 16:04 UTC, azenyem commented
@mhmdAljefri @hand-dot could you finish the merging process please? I would like to add two more languages...

Fields `plsSelect`, `plsAddNewField`, `goToFirst`, `goToPrevious`, `goToNext`, `goToEnd`, `select`, `zoomIn`, `zoomOut` became obsolete since the pull request.

Thank you

2023-05-13 02:54 UTC, hand-dot commented
Sorry for the late reply...
I will merge it since it looks like you have reviewed it!

I will include it in the next release, so please wait a little longer for the release!

2023-05-13 02:56 UTC, merged