Enable placement of headers and footers in fixed positions
pdfme/pdfme pull request #620
Opened 2024-11-04 05:25 UTC by hand-dot

ref: #591

2024-11-04 13:04 UTC, hand-dot commented on packages/common/src/helper.ts
> +export const replacePlaceholders = (arg: {
ref https://github.com/pdfme/pdfme/issues/621

2024-11-05 01:37 UTC, hand-dot commented on packages/common/src/helper.ts
> +export const replacePlaceholders = (arg: {
This function is currently used to utilize variables in staticSchema.

2024-11-05 01:37 UTC, hand-dot commented on packages/schemas/src/date/helper.ts
> +    const dateTimePattern = /^\d{4}\/\d{2}\/\d{2} \d{2}:\d{2}$/;
This change is not directly related to this PR.

2024-11-05 01:40 UTC, hand-dot commented
Hi @peteward ,

If you have time, could you review this?
You can test it by setting the Template Preset to *Invoice* in the playground.

![CleanShot 2024-11-05 at 10 38 57@2x](https://github.com/user-attachments/assets/6104da7f-4b6d-4ef8-b4af-4d4309437c85)

2024-11-05 17:54 UTC, peteward reviewed
So it seems like this adds 2 features that only work together:
* static schemas which can only be added by code, not by the UI
* placeholder content replacements that can only be used with static schemas

I was wondering why you decided to add `staticSchemas` as an explicit set of schemas rather than having a `static` boolean flag on existing schemas? These could then be placed by the designer where desired.

You could also use placeholders replacement in any text schema, it doesn't have to be limited to something static.

2024-11-06 00:54 UTC, hand-dot commented
@peteward Thank you!

> So it seems like this adds 2 features that only work together:
> 
> * static schemas which can only be added by code, not by the UI
> * placeholder content replacements that can only be used with static schemas
> 
> I was wondering why you decided to add `staticSchemas` as an explicit set of schemas rather than having a `static` boolean flag on existing schemas? These could then be placed by the designer where desired.
> 
> You could also use placeholders replacement in any text schema, it doesn't have to be limited to something static.

Explain the reason for adding `staticSchemas` as an explicit schema set.

By placing `staticSchemas` within the `padding`, it works correctly without elements overlapping, even when the schema count changes in combination with page breaks. 

![CleanShot 2024-11-06 at 09 35 57](https://github.com/user-attachments/assets/0685b272-5cff-4293-92fd-f2efbea02e34)

For this reason, I believe `staticSchemas` should be considered a special element that can be placed within the `padding`, distinct from other schemas.

Additionally, from a data structure perspective, it feels natural to include `staticSchemas` within `basePdf`. This approach also eliminates the need to refer to a static flag within schemas to branch logic during page break processing.

Currently, even though `staticSchemas` cannot be manipulated by designers, the present data structure is simpler. In the future, enabling designers to edit the `padding` and `staticSchemas` in `basePdf` may improve usability.

Regarding placeholders, they are planned to be available across all schemas by integrating with EJS as part of the issue response here:  
https://github.com/pdfme/pdfme/issues/621

2024-11-11 01:50 UTC, hand-dot commented
Hi @peteward 
I have also added the expression feature to this PR (to use expressions within staticSchema).

Could you review it again? 
I’d appreciate it if you could check for any potential security issues as part of the review.

2024-11-11 09:29 UTC, peteward approved these changes
amazing work! 🎉

2024-11-11 09:43 UTC, peteward requested changes

2024-11-11 09:43 UTC, peteward commented on website/docs/headers-and-footers.md
> +      "content": "Page {page} of {total}",
```suggestion
      "content": "Page {currentPage} of {totalPages}",
```

2024-11-11 09:43 UTC, peteward commented on playground/src/helper.ts
> +        content: 'Page {page} of {total}',
```suggestion
        content: 'Page {currentPage} of {totalPages}',
```

2024-11-11 09:46 UTC, hand-dot commented on website/docs/headers-and-footers.md
> +      "content": "Page {page} of {total}",
Good catch! Thank you

I will fix.

2024-11-11 10:19 UTC, merged